# Generated by Django 4.2.5 on 2023-10-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='Familia',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='Hermanos',
            new_name='Tiene_hermanos',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='Hijos',
            new_name='Tiene_hijos',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='Pareja',
            new_name='Tiene_pareja',
        ),
    ]
