# Generated by Django 4.2.5 on 2023-10-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_persona', '0002_rename_familia_familia_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='Tiene_hermanos',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='Tiene_pareja',
        ),
        migrations.AddField(
            model_name='familia',
            name='Pareja',
            field=models.TextField(blank=True),
        ),
    ]
